apiVersion: v1
kind: Secret
metadata:
  name: controle-arquivos-secret
  namespace: controle-arquivos
type: Opaque
# Valores em base64: echo -n "valor" | base64
stringData:
  DB_USER: controle_arquivos
  DB_PASSWORD: controle_arquivos
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
