apiVersion: v1
kind: Service
metadata:
  name: controle-arquivos-orchestrator
  labels:
    app: controle-arquivos
    component: orchestrator
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: controle-arquivos
    component: orchestrator
