apiVersion: v1
kind: Service
metadata:
  name: controle-arquivos-processor
  labels:
    app: controle-arquivos
    component: processor
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: controle-arquivos
    component: processor
